### ISSUE TITLE
Example of Running Cascade

### ISSUE THREAD

**Issue by samanthamolnar** [yangyangangela/continuous_cascade_model#1]
Hi Dr. Yang,

This isn't an issue more of a question that I have. 

To run a cascade would I run your code in the following way:

`
% setup case
S = stateV1('case39');
time_length = 10;
E = edge_list(S);  % get the edgelist
I = E('from');J=E('to');IJ=[I J];
line = IJ(4,:);% select a line.
line2 = IJ(28,:);

S.x = turn_off_lines(S,line);    % update the state x
S.x = turn_off_lines(S,line2);  % update the state x
[Tspan, Y2] = solve_dynamic(S,time_length);
`

Does the code automatically turn lines off if they are overloaded or do I need to set that up manually when I run a case?  If so, do you think you could give an example?  Thanks for you help and appreciate the code!

**Comment by QiangLi19326** [comment]
Hi Dr. Yang,

`
% setup case
S = stateV1('case39');
E = edge_list(S);% get the edgelist
I = E('from');J=E('to');IJ=[I J];
line = IJ(24,:);% select a line.
S.x = turn_off_lines(S,line);% update the state x
line = IJ(26,:);% select a line.
S.x = turn_off_lines(S,line);% update the state x
time_length = 10;
[Tspan_cascade, Y1_cascade] = solve_dynamic(S,time_length);
`
When I run your code above, there is no cascading failures.  Does the code automatically turn lines off if they are overloaded ?  Could you give an example? Thanks for your help and appreciate the code.

**Comment by QiangLi19326** [comment]
Hi Dr. Yang,

`
% setup case S = stateV1('case39'); 
E = edge_list(S);% get the edgelist 
I = E('from');J=E('to');IJ=[I J];
 line = IJ(24,:);% select a line.
 S.x = turn_off_lines(S,line);% update the state x 
line = IJ(26,:);% select a line. 
S.x = turn_off_lines(S,line);% update the state x 
time_length = 10; 
[Tspan_cascade, Y1_cascade] = solve_dynamic(S,time_length);
`

When I run your code above, there is no cascading failures. Does the code automatically turn lines off if they are overloaded ? Could you give an example? Thanks for your help and appreciate the code.

**Comment by QiangLi19326** [comment]
Hi Dr. Yang,

```
% setup case S = stateV1('case39'); 
E = edge_list(S);% get the edgelist 
I = E('from');J=E('to');IJ=[I J];
 line = IJ(24,:);% select a line.
 S.x = turn_off_lines(S,line);% update the state x 
line = IJ(26,:);% select a line. 
S.x = turn_off_lines(S,line);% update the state x 
time_length = 10; 
[Tspan_cascade, Y1_cascade] = solve_dynamic(S,time_length);
```

When I run your code above, there is no cascading failures. Does the code automatically turn lines off if they are overloaded ? Could you give an example? Thanks for your help and appreciate the code.

**Comment by QiangLi19326** [comment]
Hi Dr. Yang,

```
% setup case 
S = stateV1('case39'); 
E = edge_list(S);% get the edgelist 
I = E('from');J=E('to');IJ=[I J];
line = IJ(24,:);% select a line.
S.x = turn_off_lines(S,line);% update the state x 
line = IJ(26,:);% select a line. 
S.x = turn_off_lines(S,line);% update the state x 
time_length = 10; 
[Tspan_cascade, Y1_cascade] = solve_dynamic(S,time_length);
```

When I run your code above, there is no cascading failures. Does the code automatically turn lines off if they are overloaded ? Could you give an example? Thanks for your help and appreciate the code.
